/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "xobideeruujumsjxtbfu"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvYmlkZWVydXVqdW1zanh0YmZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgwNTQzOTMsImV4cCI6MjA4MzYzMDM5M30.Url2M-SkqfxZKBpL3mZ-bHKYLE9vqrRlfkv9JX5XZDs"